// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Birthday             string   `protobuf:"bytes,3,opt,name=birthday,proto3" json:"birthday,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Username             string   `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,7,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Photo                string   `protobuf:"bytes,8,opt,name=photo,proto3" json:"photo,omitempty"`
	AvailableMb          uint32   `protobuf:"varint,9,opt,name=available_mb,json=availableMb,proto3" json:"available_mb,omitempty"`
	IsAdmin              bool     `protobuf:"varint,10,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	IsLocked             bool     `protobuf:"varint,11,opt,name=is_locked,json=isLocked,proto3" json:"is_locked,omitempty"`
	IsActivated          bool     `protobuf:"varint,12,opt,name=is_activated,json=isActivated,proto3" json:"is_activated,omitempty"`
	LastLogin            string   `protobuf:"bytes,13,opt,name=last_login,json=lastLogin,proto3" json:"last_login,omitempty"`
	LastEdited           string   `protobuf:"bytes,14,opt,name=last_edited,json=lastEdited,proto3" json:"last_edited,omitempty"`
	Created              string   `protobuf:"bytes,15,opt,name=created,proto3" json:"created,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetBirthday() string {
	if m != nil {
		return m.Birthday
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *User) GetPhoto() string {
	if m != nil {
		return m.Photo
	}
	return ""
}

func (m *User) GetAvailableMb() uint32 {
	if m != nil {
		return m.AvailableMb
	}
	return 0
}

func (m *User) GetIsAdmin() bool {
	if m != nil {
		return m.IsAdmin
	}
	return false
}

func (m *User) GetIsLocked() bool {
	if m != nil {
		return m.IsLocked
	}
	return false
}

func (m *User) GetIsActivated() bool {
	if m != nil {
		return m.IsActivated
	}
	return false
}

func (m *User) GetLastLogin() string {
	if m != nil {
		return m.LastLogin
	}
	return ""
}

func (m *User) GetLastEdited() string {
	if m != nil {
		return m.LastEdited
	}
	return ""
}

func (m *User) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

type CreateAccountRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	CreationDate         string   `protobuf:"bytes,2,opt,name=creation_date,json=creationDate,proto3" json:"creation_date,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAccountRequest) Reset()         { *m = CreateAccountRequest{} }
func (m *CreateAccountRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAccountRequest) ProtoMessage()    {}
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *CreateAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountRequest.Unmarshal(m, b)
}
func (m *CreateAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountRequest.Marshal(b, m, deterministic)
}
func (m *CreateAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountRequest.Merge(m, src)
}
func (m *CreateAccountRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAccountRequest.Size(m)
}
func (m *CreateAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountRequest proto.InternalMessageInfo

func (m *CreateAccountRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *CreateAccountRequest) GetCreationDate() string {
	if m != nil {
		return m.CreationDate
	}
	return ""
}

type CreateAccountResponse struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAccountResponse) Reset()         { *m = CreateAccountResponse{} }
func (m *CreateAccountResponse) String() string { return proto.CompactTextString(m) }
func (*CreateAccountResponse) ProtoMessage()    {}
func (*CreateAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *CreateAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountResponse.Unmarshal(m, b)
}
func (m *CreateAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountResponse.Marshal(b, m, deterministic)
}
func (m *CreateAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountResponse.Merge(m, src)
}
func (m *CreateAccountResponse) XXX_Size() int {
	return xxx_messageInfo_CreateAccountResponse.Size(m)
}
func (m *CreateAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountResponse proto.InternalMessageInfo

func (m *CreateAccountResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type ActivateAccountRequest struct {
	ActivationToken      string   `protobuf:"bytes,1,opt,name=activation_token,json=activationToken,proto3" json:"activation_token,omitempty"`
	ActivationDate       string   `protobuf:"bytes,2,opt,name=activation_date,json=activationDate,proto3" json:"activation_date,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActivateAccountRequest) Reset()         { *m = ActivateAccountRequest{} }
func (m *ActivateAccountRequest) String() string { return proto.CompactTextString(m) }
func (*ActivateAccountRequest) ProtoMessage()    {}
func (*ActivateAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{3}
}

func (m *ActivateAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActivateAccountRequest.Unmarshal(m, b)
}
func (m *ActivateAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActivateAccountRequest.Marshal(b, m, deterministic)
}
func (m *ActivateAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActivateAccountRequest.Merge(m, src)
}
func (m *ActivateAccountRequest) XXX_Size() int {
	return xxx_messageInfo_ActivateAccountRequest.Size(m)
}
func (m *ActivateAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ActivateAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ActivateAccountRequest proto.InternalMessageInfo

func (m *ActivateAccountRequest) GetActivationToken() string {
	if m != nil {
		return m.ActivationToken
	}
	return ""
}

func (m *ActivateAccountRequest) GetActivationDate() string {
	if m != nil {
		return m.ActivationDate
	}
	return ""
}

type ActivateAccountResponse struct {
	SessionToken         string   `protobuf:"bytes,1,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActivateAccountResponse) Reset()         { *m = ActivateAccountResponse{} }
func (m *ActivateAccountResponse) String() string { return proto.CompactTextString(m) }
func (*ActivateAccountResponse) ProtoMessage()    {}
func (*ActivateAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{4}
}

func (m *ActivateAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActivateAccountResponse.Unmarshal(m, b)
}
func (m *ActivateAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActivateAccountResponse.Marshal(b, m, deterministic)
}
func (m *ActivateAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActivateAccountResponse.Merge(m, src)
}
func (m *ActivateAccountResponse) XXX_Size() int {
	return xxx_messageInfo_ActivateAccountResponse.Size(m)
}
func (m *ActivateAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ActivateAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ActivateAccountResponse proto.InternalMessageInfo

func (m *ActivateAccountResponse) GetSessionToken() string {
	if m != nil {
		return m.SessionToken
	}
	return ""
}

type ResendActivationMailRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResendActivationMailRequest) Reset()         { *m = ResendActivationMailRequest{} }
func (m *ResendActivationMailRequest) String() string { return proto.CompactTextString(m) }
func (*ResendActivationMailRequest) ProtoMessage()    {}
func (*ResendActivationMailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{5}
}

func (m *ResendActivationMailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResendActivationMailRequest.Unmarshal(m, b)
}
func (m *ResendActivationMailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResendActivationMailRequest.Marshal(b, m, deterministic)
}
func (m *ResendActivationMailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResendActivationMailRequest.Merge(m, src)
}
func (m *ResendActivationMailRequest) XXX_Size() int {
	return xxx_messageInfo_ResendActivationMailRequest.Size(m)
}
func (m *ResendActivationMailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResendActivationMailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResendActivationMailRequest proto.InternalMessageInfo

func (m *ResendActivationMailRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type ResendActivationMailResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResendActivationMailResponse) Reset()         { *m = ResendActivationMailResponse{} }
func (m *ResendActivationMailResponse) String() string { return proto.CompactTextString(m) }
func (*ResendActivationMailResponse) ProtoMessage()    {}
func (*ResendActivationMailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{6}
}

func (m *ResendActivationMailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResendActivationMailResponse.Unmarshal(m, b)
}
func (m *ResendActivationMailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResendActivationMailResponse.Marshal(b, m, deterministic)
}
func (m *ResendActivationMailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResendActivationMailResponse.Merge(m, src)
}
func (m *ResendActivationMailResponse) XXX_Size() int {
	return xxx_messageInfo_ResendActivationMailResponse.Size(m)
}
func (m *ResendActivationMailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ResendActivationMailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ResendActivationMailResponse proto.InternalMessageInfo

type UpdateAccountRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	CreationDate         string   `protobuf:"bytes,2,opt,name=creation_date,json=creationDate,proto3" json:"creation_date,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateAccountRequest) Reset()         { *m = UpdateAccountRequest{} }
func (m *UpdateAccountRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateAccountRequest) ProtoMessage()    {}
func (*UpdateAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{7}
}

func (m *UpdateAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAccountRequest.Unmarshal(m, b)
}
func (m *UpdateAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAccountRequest.Marshal(b, m, deterministic)
}
func (m *UpdateAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAccountRequest.Merge(m, src)
}
func (m *UpdateAccountRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateAccountRequest.Size(m)
}
func (m *UpdateAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAccountRequest proto.InternalMessageInfo

func (m *UpdateAccountRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *UpdateAccountRequest) GetCreationDate() string {
	if m != nil {
		return m.CreationDate
	}
	return ""
}

type UpdateAccountResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateAccountResponse) Reset()         { *m = UpdateAccountResponse{} }
func (m *UpdateAccountResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateAccountResponse) ProtoMessage()    {}
func (*UpdateAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{8}
}

func (m *UpdateAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAccountResponse.Unmarshal(m, b)
}
func (m *UpdateAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAccountResponse.Marshal(b, m, deterministic)
}
func (m *UpdateAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAccountResponse.Merge(m, src)
}
func (m *UpdateAccountResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateAccountResponse.Size(m)
}
func (m *UpdateAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAccountResponse proto.InternalMessageInfo

type DeleteAccountRequest struct {
	SessionToken         string   `protobuf:"bytes,1,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAccountRequest) Reset()         { *m = DeleteAccountRequest{} }
func (m *DeleteAccountRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteAccountRequest) ProtoMessage()    {}
func (*DeleteAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{9}
}

func (m *DeleteAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAccountRequest.Unmarshal(m, b)
}
func (m *DeleteAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAccountRequest.Marshal(b, m, deterministic)
}
func (m *DeleteAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAccountRequest.Merge(m, src)
}
func (m *DeleteAccountRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteAccountRequest.Size(m)
}
func (m *DeleteAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAccountRequest proto.InternalMessageInfo

func (m *DeleteAccountRequest) GetSessionToken() string {
	if m != nil {
		return m.SessionToken
	}
	return ""
}

type DeleteAccountResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAccountResponse) Reset()         { *m = DeleteAccountResponse{} }
func (m *DeleteAccountResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteAccountResponse) ProtoMessage()    {}
func (*DeleteAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{10}
}

func (m *DeleteAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAccountResponse.Unmarshal(m, b)
}
func (m *DeleteAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAccountResponse.Marshal(b, m, deterministic)
}
func (m *DeleteAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAccountResponse.Merge(m, src)
}
func (m *DeleteAccountResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteAccountResponse.Size(m)
}
func (m *DeleteAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAccountResponse proto.InternalMessageInfo

type GetAccountRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccountRequest) Reset()         { *m = GetAccountRequest{} }
func (m *GetAccountRequest) String() string { return proto.CompactTextString(m) }
func (*GetAccountRequest) ProtoMessage()    {}
func (*GetAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{11}
}

func (m *GetAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountRequest.Unmarshal(m, b)
}
func (m *GetAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountRequest.Marshal(b, m, deterministic)
}
func (m *GetAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountRequest.Merge(m, src)
}
func (m *GetAccountRequest) XXX_Size() int {
	return xxx_messageInfo_GetAccountRequest.Size(m)
}
func (m *GetAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountRequest proto.InternalMessageInfo

func (m *GetAccountRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetAccountResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccountResponse) Reset()         { *m = GetAccountResponse{} }
func (m *GetAccountResponse) String() string { return proto.CompactTextString(m) }
func (*GetAccountResponse) ProtoMessage()    {}
func (*GetAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{12}
}

func (m *GetAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountResponse.Unmarshal(m, b)
}
func (m *GetAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountResponse.Marshal(b, m, deterministic)
}
func (m *GetAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountResponse.Merge(m, src)
}
func (m *GetAccountResponse) XXX_Size() int {
	return xxx_messageInfo_GetAccountResponse.Size(m)
}
func (m *GetAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountResponse proto.InternalMessageInfo

func (m *GetAccountResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type LoginRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{13}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	SessionToken         string   `protobuf:"bytes,1,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{14}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetSessionToken() string {
	if m != nil {
		return m.SessionToken
	}
	return ""
}

type LogoutRequest struct {
	SessionToken         string   `protobuf:"bytes,1,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutRequest) Reset()         { *m = LogoutRequest{} }
func (m *LogoutRequest) String() string { return proto.CompactTextString(m) }
func (*LogoutRequest) ProtoMessage()    {}
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{15}
}

func (m *LogoutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutRequest.Unmarshal(m, b)
}
func (m *LogoutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutRequest.Marshal(b, m, deterministic)
}
func (m *LogoutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutRequest.Merge(m, src)
}
func (m *LogoutRequest) XXX_Size() int {
	return xxx_messageInfo_LogoutRequest.Size(m)
}
func (m *LogoutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutRequest proto.InternalMessageInfo

func (m *LogoutRequest) GetSessionToken() string {
	if m != nil {
		return m.SessionToken
	}
	return ""
}

type LogoutResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutResponse) Reset()         { *m = LogoutResponse{} }
func (m *LogoutResponse) String() string { return proto.CompactTextString(m) }
func (*LogoutResponse) ProtoMessage()    {}
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{16}
}

func (m *LogoutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutResponse.Unmarshal(m, b)
}
func (m *LogoutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutResponse.Marshal(b, m, deterministic)
}
func (m *LogoutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutResponse.Merge(m, src)
}
func (m *LogoutResponse) XXX_Size() int {
	return xxx_messageInfo_LogoutResponse.Size(m)
}
func (m *LogoutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutResponse proto.InternalMessageInfo

type ResetPasswordRequest struct {
	SessionToken         string   `protobuf:"bytes,1,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	OldPassword          string   `protobuf:"bytes,3,opt,name=old_password,json=oldPassword,proto3" json:"old_password,omitempty"`
	NewPassword          string   `protobuf:"bytes,4,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetPasswordRequest) Reset()         { *m = ResetPasswordRequest{} }
func (m *ResetPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ResetPasswordRequest) ProtoMessage()    {}
func (*ResetPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{17}
}

func (m *ResetPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetPasswordRequest.Unmarshal(m, b)
}
func (m *ResetPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetPasswordRequest.Marshal(b, m, deterministic)
}
func (m *ResetPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetPasswordRequest.Merge(m, src)
}
func (m *ResetPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ResetPasswordRequest.Size(m)
}
func (m *ResetPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResetPasswordRequest proto.InternalMessageInfo

func (m *ResetPasswordRequest) GetSessionToken() string {
	if m != nil {
		return m.SessionToken
	}
	return ""
}

func (m *ResetPasswordRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *ResetPasswordRequest) GetOldPassword() string {
	if m != nil {
		return m.OldPassword
	}
	return ""
}

func (m *ResetPasswordRequest) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

type ResetPasswordResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetPasswordResponse) Reset()         { *m = ResetPasswordResponse{} }
func (m *ResetPasswordResponse) String() string { return proto.CompactTextString(m) }
func (*ResetPasswordResponse) ProtoMessage()    {}
func (*ResetPasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{18}
}

func (m *ResetPasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetPasswordResponse.Unmarshal(m, b)
}
func (m *ResetPasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetPasswordResponse.Marshal(b, m, deterministic)
}
func (m *ResetPasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetPasswordResponse.Merge(m, src)
}
func (m *ResetPasswordResponse) XXX_Size() int {
	return xxx_messageInfo_ResetPasswordResponse.Size(m)
}
func (m *ResetPasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetPasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ResetPasswordResponse proto.InternalMessageInfo

type LockAccountRequest struct {
	SessionToken         string   `protobuf:"bytes,1,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LockAccountRequest) Reset()         { *m = LockAccountRequest{} }
func (m *LockAccountRequest) String() string { return proto.CompactTextString(m) }
func (*LockAccountRequest) ProtoMessage()    {}
func (*LockAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{19}
}

func (m *LockAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LockAccountRequest.Unmarshal(m, b)
}
func (m *LockAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LockAccountRequest.Marshal(b, m, deterministic)
}
func (m *LockAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LockAccountRequest.Merge(m, src)
}
func (m *LockAccountRequest) XXX_Size() int {
	return xxx_messageInfo_LockAccountRequest.Size(m)
}
func (m *LockAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LockAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LockAccountRequest proto.InternalMessageInfo

func (m *LockAccountRequest) GetSessionToken() string {
	if m != nil {
		return m.SessionToken
	}
	return ""
}

func (m *LockAccountRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type LockAccountResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LockAccountResponse) Reset()         { *m = LockAccountResponse{} }
func (m *LockAccountResponse) String() string { return proto.CompactTextString(m) }
func (*LockAccountResponse) ProtoMessage()    {}
func (*LockAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{20}
}

func (m *LockAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LockAccountResponse.Unmarshal(m, b)
}
func (m *LockAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LockAccountResponse.Marshal(b, m, deterministic)
}
func (m *LockAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LockAccountResponse.Merge(m, src)
}
func (m *LockAccountResponse) XXX_Size() int {
	return xxx_messageInfo_LockAccountResponse.Size(m)
}
func (m *LockAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LockAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LockAccountResponse proto.InternalMessageInfo

type UnlockAccountRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	SessionToken         string   `protobuf:"bytes,2,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	UserId               string   `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnlockAccountRequest) Reset()         { *m = UnlockAccountRequest{} }
func (m *UnlockAccountRequest) String() string { return proto.CompactTextString(m) }
func (*UnlockAccountRequest) ProtoMessage()    {}
func (*UnlockAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{21}
}

func (m *UnlockAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnlockAccountRequest.Unmarshal(m, b)
}
func (m *UnlockAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnlockAccountRequest.Marshal(b, m, deterministic)
}
func (m *UnlockAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnlockAccountRequest.Merge(m, src)
}
func (m *UnlockAccountRequest) XXX_Size() int {
	return xxx_messageInfo_UnlockAccountRequest.Size(m)
}
func (m *UnlockAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnlockAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnlockAccountRequest proto.InternalMessageInfo

func (m *UnlockAccountRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UnlockAccountRequest) GetSessionToken() string {
	if m != nil {
		return m.SessionToken
	}
	return ""
}

func (m *UnlockAccountRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type UnlockAccountResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnlockAccountResponse) Reset()         { *m = UnlockAccountResponse{} }
func (m *UnlockAccountResponse) String() string { return proto.CompactTextString(m) }
func (*UnlockAccountResponse) ProtoMessage()    {}
func (*UnlockAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{22}
}

func (m *UnlockAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnlockAccountResponse.Unmarshal(m, b)
}
func (m *UnlockAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnlockAccountResponse.Marshal(b, m, deterministic)
}
func (m *UnlockAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnlockAccountResponse.Merge(m, src)
}
func (m *UnlockAccountResponse) XXX_Size() int {
	return xxx_messageInfo_UnlockAccountResponse.Size(m)
}
func (m *UnlockAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UnlockAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UnlockAccountResponse proto.InternalMessageInfo

type RequestUnlockAccountRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestUnlockAccountRequest) Reset()         { *m = RequestUnlockAccountRequest{} }
func (m *RequestUnlockAccountRequest) String() string { return proto.CompactTextString(m) }
func (*RequestUnlockAccountRequest) ProtoMessage()    {}
func (*RequestUnlockAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{23}
}

func (m *RequestUnlockAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestUnlockAccountRequest.Unmarshal(m, b)
}
func (m *RequestUnlockAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestUnlockAccountRequest.Marshal(b, m, deterministic)
}
func (m *RequestUnlockAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestUnlockAccountRequest.Merge(m, src)
}
func (m *RequestUnlockAccountRequest) XXX_Size() int {
	return xxx_messageInfo_RequestUnlockAccountRequest.Size(m)
}
func (m *RequestUnlockAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestUnlockAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RequestUnlockAccountRequest proto.InternalMessageInfo

func (m *RequestUnlockAccountRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *RequestUnlockAccountRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type RequestUnlockAccountResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestUnlockAccountResponse) Reset()         { *m = RequestUnlockAccountResponse{} }
func (m *RequestUnlockAccountResponse) String() string { return proto.CompactTextString(m) }
func (*RequestUnlockAccountResponse) ProtoMessage()    {}
func (*RequestUnlockAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{24}
}

func (m *RequestUnlockAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestUnlockAccountResponse.Unmarshal(m, b)
}
func (m *RequestUnlockAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestUnlockAccountResponse.Marshal(b, m, deterministic)
}
func (m *RequestUnlockAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestUnlockAccountResponse.Merge(m, src)
}
func (m *RequestUnlockAccountResponse) XXX_Size() int {
	return xxx_messageInfo_RequestUnlockAccountResponse.Size(m)
}
func (m *RequestUnlockAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestUnlockAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RequestUnlockAccountResponse proto.InternalMessageInfo

type ListUsersRequest struct {
	SessionToken         string   `protobuf:"bytes,1,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUsersRequest) Reset()         { *m = ListUsersRequest{} }
func (m *ListUsersRequest) String() string { return proto.CompactTextString(m) }
func (*ListUsersRequest) ProtoMessage()    {}
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{25}
}

func (m *ListUsersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUsersRequest.Unmarshal(m, b)
}
func (m *ListUsersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUsersRequest.Marshal(b, m, deterministic)
}
func (m *ListUsersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUsersRequest.Merge(m, src)
}
func (m *ListUsersRequest) XXX_Size() int {
	return xxx_messageInfo_ListUsersRequest.Size(m)
}
func (m *ListUsersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUsersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListUsersRequest proto.InternalMessageInfo

func (m *ListUsersRequest) GetSessionToken() string {
	if m != nil {
		return m.SessionToken
	}
	return ""
}

type ListUsersResponse struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUsersResponse) Reset()         { *m = ListUsersResponse{} }
func (m *ListUsersResponse) String() string { return proto.CompactTextString(m) }
func (*ListUsersResponse) ProtoMessage()    {}
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{26}
}

func (m *ListUsersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUsersResponse.Unmarshal(m, b)
}
func (m *ListUsersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUsersResponse.Marshal(b, m, deterministic)
}
func (m *ListUsersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUsersResponse.Merge(m, src)
}
func (m *ListUsersResponse) XXX_Size() int {
	return xxx_messageInfo_ListUsersResponse.Size(m)
}
func (m *ListUsersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUsersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListUsersResponse proto.InternalMessageInfo

func (m *ListUsersResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "account_service.User")
	proto.RegisterType((*CreateAccountRequest)(nil), "account_service.CreateAccountRequest")
	proto.RegisterType((*CreateAccountResponse)(nil), "account_service.CreateAccountResponse")
	proto.RegisterType((*ActivateAccountRequest)(nil), "account_service.ActivateAccountRequest")
	proto.RegisterType((*ActivateAccountResponse)(nil), "account_service.ActivateAccountResponse")
	proto.RegisterType((*ResendActivationMailRequest)(nil), "account_service.ResendActivationMailRequest")
	proto.RegisterType((*ResendActivationMailResponse)(nil), "account_service.ResendActivationMailResponse")
	proto.RegisterType((*UpdateAccountRequest)(nil), "account_service.UpdateAccountRequest")
	proto.RegisterType((*UpdateAccountResponse)(nil), "account_service.UpdateAccountResponse")
	proto.RegisterType((*DeleteAccountRequest)(nil), "account_service.DeleteAccountRequest")
	proto.RegisterType((*DeleteAccountResponse)(nil), "account_service.DeleteAccountResponse")
	proto.RegisterType((*GetAccountRequest)(nil), "account_service.GetAccountRequest")
	proto.RegisterType((*GetAccountResponse)(nil), "account_service.GetAccountResponse")
	proto.RegisterType((*LoginRequest)(nil), "account_service.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "account_service.LoginResponse")
	proto.RegisterType((*LogoutRequest)(nil), "account_service.LogoutRequest")
	proto.RegisterType((*LogoutResponse)(nil), "account_service.LogoutResponse")
	proto.RegisterType((*ResetPasswordRequest)(nil), "account_service.ResetPasswordRequest")
	proto.RegisterType((*ResetPasswordResponse)(nil), "account_service.ResetPasswordResponse")
	proto.RegisterType((*LockAccountRequest)(nil), "account_service.LockAccountRequest")
	proto.RegisterType((*LockAccountResponse)(nil), "account_service.LockAccountResponse")
	proto.RegisterType((*UnlockAccountRequest)(nil), "account_service.UnlockAccountRequest")
	proto.RegisterType((*UnlockAccountResponse)(nil), "account_service.UnlockAccountResponse")
	proto.RegisterType((*RequestUnlockAccountRequest)(nil), "account_service.RequestUnlockAccountRequest")
	proto.RegisterType((*RequestUnlockAccountResponse)(nil), "account_service.RequestUnlockAccountResponse")
	proto.RegisterType((*ListUsersRequest)(nil), "account_service.ListUsersRequest")
	proto.RegisterType((*ListUsersResponse)(nil), "account_service.ListUsersResponse")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 1125 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x57, 0xcd, 0x6e, 0x23, 0x45,
	0x10, 0xd6, 0x38, 0x3f, 0xb6, 0xcb, 0x76, 0x92, 0xed, 0xb5, 0xf1, 0xec, 0x64, 0x9d, 0x38, 0xe3,
	0xdd, 0xac, 0xf9, 0x8b, 0x61, 0x17, 0x09, 0x09, 0x24, 0x20, 0xb0, 0x80, 0x90, 0xb2, 0xcb, 0xca,
	0x22, 0x17, 0x2e, 0xd6, 0xd8, 0xd3, 0x49, 0x9a, 0x1d, 0x4f, 0x9b, 0xe9, 0x71, 0x02, 0x17, 0x0e,
	0x20, 0x71, 0xe1, 0xc8, 0x81, 0x03, 0x47, 0x9e, 0x83, 0x33, 0x0f, 0xc0, 0x2b, 0xf0, 0x20, 0xa8,
	0x6b, 0x7a, 0xec, 0xf9, 0x69, 0x3b, 0x36, 0x12, 0x37, 0x77, 0xfd, 0x7d, 0x5f, 0x57, 0x55, 0x57,
	0x8d, 0xa1, 0x26, 0x68, 0x70, 0xcd, 0x46, 0xf4, 0x64, 0x12, 0xf0, 0x90, 0x93, 0x5d, 0x67, 0x34,
	0xe2, 0x53, 0x3f, 0x1c, 0x28, 0xb1, 0x75, 0xff, 0x92, 0xf3, 0x4b, 0x8f, 0xf6, 0x9c, 0x09, 0xeb,
	0x39, 0xbe, 0xcf, 0x43, 0x27, 0x64, 0xdc, 0x17, 0x91, 0xb9, 0xfd, 0xe7, 0x06, 0x6c, 0x9e, 0x0b,
	0x1a, 0x90, 0x16, 0xc0, 0x05, 0x0b, 0x44, 0x38, 0xf0, 0x9d, 0x31, 0x35, 0x8d, 0xb6, 0xd1, 0x2d,
	0xf7, 0xcb, 0x28, 0x79, 0xee, 0x8c, 0x29, 0xd9, 0x87, 0xb2, 0xe7, 0xc4, 0xda, 0x02, 0x6a, 0x4b,
	0x52, 0x80, 0x4a, 0x0b, 0x4a, 0x43, 0x16, 0x84, 0x57, 0xae, 0xf3, 0xbd, 0xb9, 0x11, 0xe9, 0xe2,
	0x33, 0xa9, 0xc3, 0x16, 0x1d, 0x3b, 0xcc, 0x33, 0x37, 0x51, 0x11, 0x1d, 0xa4, 0xc7, 0x54, 0xd0,
	0x00, 0xa3, 0x6d, 0x45, 0x1e, 0xf1, 0x59, 0xea, 0x26, 0x8e, 0x10, 0x37, 0x3c, 0x70, 0xcd, 0xed,
	0x48, 0x17, 0x9f, 0xc9, 0x11, 0x54, 0x27, 0x57, 0xdc, 0xa7, 0x03, 0x7f, 0x3a, 0x1e, 0xd2, 0xc0,
	0x2c, 0xa2, 0xbe, 0x82, 0xb2, 0xe7, 0x28, 0x92, 0x80, 0x93, 0x2b, 0x1e, 0x72, 0xb3, 0x14, 0x01,
	0xe2, 0x41, 0x3a, 0x3a, 0xd7, 0x0e, 0xf3, 0x9c, 0xa1, 0x47, 0x07, 0xe3, 0xa1, 0x59, 0x6e, 0x1b,
	0xdd, 0x5a, 0xbf, 0x32, 0x93, 0x3d, 0x1b, 0x92, 0x7b, 0x50, 0x62, 0x62, 0xe0, 0xb8, 0x63, 0xe6,
	0x9b, 0xd0, 0x36, 0xba, 0xa5, 0x7e, 0x91, 0x89, 0x53, 0x79, 0x94, 0xb7, 0x67, 0x62, 0xe0, 0xf1,
	0xd1, 0x4b, 0xea, 0x9a, 0x15, 0xd4, 0x95, 0x98, 0x38, 0xc3, 0xb3, 0x0c, 0x2d, 0xfd, 0x46, 0x21,
	0xbb, 0x76, 0x42, 0xea, 0x9a, 0x55, 0xd4, 0x57, 0x98, 0x38, 0x8d, 0x45, 0x32, 0xb9, 0x98, 0x3d,
	0x8f, 0x5f, 0x32, 0xdf, 0xac, 0x45, 0xc9, 0x95, 0x92, 0x33, 0x29, 0x20, 0x87, 0x50, 0x41, 0x35,
	0x75, 0x99, 0x0c, 0xb0, 0x83, 0x7a, 0xf4, 0xf8, 0x14, 0x25, 0xc4, 0x84, 0xe2, 0x28, 0xa0, 0x18,
	0x7d, 0x17, 0x95, 0xf1, 0xd1, 0xbe, 0x80, 0xfa, 0x27, 0xf8, 0xf3, 0x34, 0x2a, 0x7b, 0x9f, 0x7e,
	0x3b, 0xa5, 0x22, 0x24, 0xaf, 0xc2, 0xa6, 0x4c, 0x28, 0x16, 0xb2, 0xf2, 0xb8, 0x71, 0x92, 0xe9,
	0x8a, 0x13, 0x59, 0xf3, 0x3e, 0x9a, 0x90, 0x0e, 0xd4, 0x30, 0x1a, 0xe3, 0xfe, 0xc0, 0x75, 0xc2,
	0xb8, 0xbc, 0xd5, 0x58, 0xf8, 0xd4, 0x09, 0xa9, 0xfd, 0x16, 0x34, 0x32, 0x38, 0x62, 0xc2, 0x7d,
	0x41, 0x49, 0x13, 0x8a, 0x32, 0xca, 0x80, 0xb9, 0xaa, 0x69, 0xb6, 0xe5, 0xf1, 0x0b, 0xd7, 0xf6,
	0xe0, 0x95, 0x38, 0x01, 0x39, 0x6e, 0x7b, 0x2a, 0x5b, 0x12, 0x32, 0xe4, 0x2f, 0xa9, 0xaf, 0x7c,
	0x77, 0xe7, 0xf2, 0xaf, 0xa4, 0x98, 0x3c, 0x82, 0x84, 0x28, 0xc9, 0x6e, 0x67, 0x2e, 0x46, 0x7e,
	0x1f, 0x40, 0x33, 0x87, 0xa6, 0x18, 0x76, 0xe4, 0x13, 0x11, 0x22, 0x8b, 0x55, 0x55, 0x42, 0x04,
	0xb2, 0x9f, 0xc0, 0x7e, 0x9f, 0x0a, 0xea, 0xbb, 0xa7, 0xb3, 0xb8, 0xcf, 0x1c, 0xe6, 0xc5, 0x94,
	0x67, 0x5d, 0x6c, 0x24, 0xba, 0xd8, 0x3e, 0x80, 0xfb, 0x7a, 0xa7, 0x08, 0x59, 0x16, 0xe7, 0x7c,
	0xe2, 0xfe, 0xff, 0xc5, 0x69, 0x42, 0x23, 0x83, 0xa3, 0x08, 0xbc, 0x0f, 0xf5, 0xa7, 0xd4, 0xa3,
	0x39, 0x02, 0x2b, 0xa5, 0xa4, 0x09, 0x8d, 0x8c, 0xb3, 0x8a, 0xda, 0x81, 0x3b, 0x9f, 0xd3, 0x30,
	0x13, 0x72, 0x07, 0x0a, 0xb3, 0x16, 0x28, 0x30, 0xd7, 0xfe, 0x10, 0x48, 0xd2, 0x48, 0xd5, 0x62,
	0xf5, 0x9b, 0xdb, 0x9f, 0x41, 0x15, 0x5f, 0x47, 0x0c, 0x90, 0x1c, 0x19, 0xc6, 0x92, 0x91, 0x51,
	0x48, 0x8f, 0x0c, 0xfb, 0x1d, 0xa8, 0xa9, 0x38, 0xeb, 0xf4, 0x43, 0xe4, 0xc5, 0xa7, 0xeb, 0xa5,
	0x6c, 0x0f, 0x76, 0x62, 0x2f, 0x95, 0xab, 0xdf, 0x0c, 0xa8, 0xcb, 0x1e, 0x09, 0x5f, 0x28, 0x3e,
	0xeb, 0xc4, 0x9b, 0xb7, 0x5d, 0x21, 0x39, 0x3c, 0x8f, 0xa0, 0xca, 0x3d, 0x77, 0x30, 0xbb, 0x71,
	0x34, 0x72, 0x2b, 0xdc, 0x73, 0x5f, 0x24, 0xe6, 0xa4, 0x4f, 0x6f, 0xe6, 0x26, 0xd1, 0xf0, 0xad,
	0xf8, 0xf4, 0x26, 0x36, 0x91, 0xe5, 0xcd, 0x10, 0x53, 0x94, 0xfb, 0x40, 0xe4, 0x64, 0xfb, 0x0f,
	0x2d, 0x93, 0x1c, 0x06, 0x85, 0xd4, 0x30, 0x68, 0xc0, 0xdd, 0x54, 0x4c, 0x05, 0xf5, 0x0d, 0xd4,
	0xcf, 0x7d, 0x2f, 0x0f, 0xa6, 0x7d, 0x6e, 0x79, 0x0a, 0x85, 0xe5, 0x14, 0x36, 0x52, 0x14, 0xe4,
	0x23, 0x49, 0x63, 0x29, 0x12, 0x5f, 0xca, 0xa7, 0x8f, 0xb8, 0x6b, 0x70, 0x59, 0xd6, 0x71, 0x38,
	0x16, 0x74, 0x01, 0x15, 0xe0, 0xbb, 0xb0, 0x77, 0xc6, 0x44, 0x28, 0x7b, 0x5d, 0xac, 0xd5, 0x5e,
	0x1f, 0xc1, 0x9d, 0x84, 0xa3, 0x6a, 0xe7, 0xd7, 0x61, 0x4b, 0xde, 0x50, 0x98, 0x46, 0x7b, 0x63,
	0xf1, 0x9b, 0x8a, 0x6c, 0x1e, 0xff, 0x55, 0x83, 0xa2, 0xa2, 0x43, 0x7e, 0x36, 0xa0, 0x96, 0x9a,
	0xe9, 0xe4, 0x61, 0xce, 0x57, 0xb7, 0x5b, 0xac, 0xe3, 0xdb, 0xcc, 0xd4, 0x3d, 0x8f, 0x7f, 0xfc,
	0xfb, 0x9f, 0x5f, 0x0b, 0x6d, 0x7b, 0xbf, 0x27, 0xc1, 0xf1, 0x03, 0xe4, 0xfa, 0xed, 0x9e, 0xf2,
	0xed, 0x45, 0x1b, 0xec, 0x3d, 0xe3, 0x35, 0xf2, 0xbb, 0x7a, 0x23, 0xd9, 0x39, 0x4a, 0xde, 0xc8,
	0x01, 0x2d, 0x99, 0xd1, 0xd6, 0x9b, 0x2b, 0x5a, 0xaf, 0xc4, 0x2e, 0x40, 0x57, 0xc9, 0xee, 0x17,
	0x03, 0x76, 0x33, 0xab, 0x85, 0x3c, 0xca, 0x41, 0xe9, 0x57, 0x9d, 0xd5, 0xbd, 0xdd, 0x50, 0xd1,
	0x79, 0x88, 0x74, 0x0e, 0x49, 0x4b, 0x4b, 0x27, 0xfe, 0xba, 0xc0, 0xa2, 0xa5, 0x66, 0xbd, 0xa6,
	0x68, 0xba, 0x9d, 0xa3, 0x29, 0x9a, 0x7e, 0x65, 0x2c, 0x4f, 0xcb, 0x14, 0x7d, 0x64, 0x5a, 0x7e,
	0x32, 0xa0, 0x96, 0x5a, 0x0f, 0x1a, 0x22, 0xba, 0xdd, 0xa3, 0x21, 0xb2, 0x60, 0xcb, 0x20, 0x91,
	0x16, 0xd1, 0x13, 0x71, 0xd1, 0x87, 0xdc, 0x00, 0xcc, 0xb7, 0x0c, 0xb1, 0x73, 0xa1, 0x73, 0x7b,
	0xca, 0xea, 0x2c, 0xb5, 0x51, 0xd8, 0x6d, 0xc4, 0xb6, 0x88, 0xa9, 0xc5, 0xbe, 0xa4, 0x21, 0xa1,
	0xb0, 0x15, 0x7d, 0xbb, 0xb5, 0x72, 0xf1, 0x92, 0x5b, 0xcb, 0x3a, 0x58, 0xa4, 0x56, 0x48, 0x2d,
	0x44, 0x6a, 0xda, 0x24, 0x85, 0x84, 0xdf, 0x89, 0x32, 0xcb, 0x17, 0xb0, 0x1d, 0x2d, 0x14, 0xa2,
	0x0d, 0x34, 0xdf, 0x4f, 0xd6, 0xe1, 0x42, 0xbd, 0x42, 0xda, 0x47, 0xa4, 0x06, 0xb9, 0x9b, 0x45,
	0x92, 0xd1, 0x65, 0x5b, 0xa5, 0xb6, 0x81, 0xa6, 0x9a, 0xba, 0x35, 0xa6, 0xa9, 0xa6, 0x7e, 0xa9,
	0xe8, 0xdb, 0x2a, 0x1e, 0x99, 0xf8, 0xdc, 0x42, 0x79, 0xe1, 0x1f, 0xa0, 0x92, 0x58, 0x14, 0xa4,
	0xa3, 0xb9, 0x55, 0x76, 0x42, 0x5b, 0x0f, 0x96, 0x1b, 0x29, 0x06, 0x0f, 0x90, 0xc1, 0x81, 0x7d,
	0x4f, 0x5b, 0x53, 0x39, 0xa7, 0x25, 0xfe, 0x1f, 0x38, 0x8b, 0xf2, 0xc3, 0x5b, 0x3b, 0x8b, 0x16,
	0x2e, 0x0d, 0xed, 0x2c, 0x5a, 0xb2, 0x11, 0x4e, 0x90, 0x5b, 0xd7, 0xee, 0xe8, 0x1f, 0x1d, 0xfa,
	0xf4, 0x82, 0x28, 0x82, 0x64, 0x89, 0x53, 0x20, 0x45, 0x4f, 0x33, 0x05, 0x74, 0xbc, 0x8e, 0x6f,
	0x33, 0x5b, 0x6d, 0x0a, 0xf8, 0x71, 0xba, 0xbe, 0x83, 0xf2, 0x6c, 0x23, 0x91, 0xa3, 0x7c, 0x1d,
	0x32, 0x6b, 0xce, 0xb2, 0x97, 0x99, 0xac, 0x56, 0x28, 0x86, 0x29, 0xf8, 0x78, 0xf3, 0xeb, 0xc2,
	0x64, 0x38, 0xdc, 0xc6, 0x7f, 0xb1, 0x4f, 0xfe, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x77, 0x18, 0x02,
	0x4e, 0x05, 0x0f, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AccountClient is the client API for Account service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountClient interface {
	CreateAccount(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*CreateAccountResponse, error)
	ResendActivationMail(ctx context.Context, in *ResendActivationMailRequest, opts ...grpc.CallOption) (*ResendActivationMailResponse, error)
	ActivateAccount(ctx context.Context, in *ActivateAccountRequest, opts ...grpc.CallOption) (*ActivateAccountResponse, error)
	UpdateAccount(ctx context.Context, in *UpdateAccountRequest, opts ...grpc.CallOption) (*UpdateAccountResponse, error)
	DeleteAccount(ctx context.Context, in *DeleteAccountRequest, opts ...grpc.CallOption) (*DeleteAccountResponse, error)
	GetAccount(ctx context.Context, in *GetAccountRequest, opts ...grpc.CallOption) (*GetAccountResponse, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error)
	ResetPassword(ctx context.Context, in *ResetPasswordRequest, opts ...grpc.CallOption) (*ResetPasswordResponse, error)
	LockAccount(ctx context.Context, in *LockAccountRequest, opts ...grpc.CallOption) (*LockAccountResponse, error)
	RequestUnlockAccount(ctx context.Context, in *RequestUnlockAccountRequest, opts ...grpc.CallOption) (*RequestUnlockAccountResponse, error)
	UnlockAccount(ctx context.Context, in *UnlockAccountRequest, opts ...grpc.CallOption) (*UnlockAccountResponse, error)
	ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error)
}

type accountClient struct {
	cc *grpc.ClientConn
}

func NewAccountClient(cc *grpc.ClientConn) AccountClient {
	return &accountClient{cc}
}

func (c *accountClient) CreateAccount(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*CreateAccountResponse, error) {
	out := new(CreateAccountResponse)
	err := c.cc.Invoke(ctx, "/account_service.Account/CreateAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) ResendActivationMail(ctx context.Context, in *ResendActivationMailRequest, opts ...grpc.CallOption) (*ResendActivationMailResponse, error) {
	out := new(ResendActivationMailResponse)
	err := c.cc.Invoke(ctx, "/account_service.Account/ResendActivationMail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) ActivateAccount(ctx context.Context, in *ActivateAccountRequest, opts ...grpc.CallOption) (*ActivateAccountResponse, error) {
	out := new(ActivateAccountResponse)
	err := c.cc.Invoke(ctx, "/account_service.Account/ActivateAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) UpdateAccount(ctx context.Context, in *UpdateAccountRequest, opts ...grpc.CallOption) (*UpdateAccountResponse, error) {
	out := new(UpdateAccountResponse)
	err := c.cc.Invoke(ctx, "/account_service.Account/UpdateAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) DeleteAccount(ctx context.Context, in *DeleteAccountRequest, opts ...grpc.CallOption) (*DeleteAccountResponse, error) {
	out := new(DeleteAccountResponse)
	err := c.cc.Invoke(ctx, "/account_service.Account/DeleteAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) GetAccount(ctx context.Context, in *GetAccountRequest, opts ...grpc.CallOption) (*GetAccountResponse, error) {
	out := new(GetAccountResponse)
	err := c.cc.Invoke(ctx, "/account_service.Account/GetAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/account_service.Account/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error) {
	out := new(LogoutResponse)
	err := c.cc.Invoke(ctx, "/account_service.Account/Logout", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) ResetPassword(ctx context.Context, in *ResetPasswordRequest, opts ...grpc.CallOption) (*ResetPasswordResponse, error) {
	out := new(ResetPasswordResponse)
	err := c.cc.Invoke(ctx, "/account_service.Account/ResetPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) LockAccount(ctx context.Context, in *LockAccountRequest, opts ...grpc.CallOption) (*LockAccountResponse, error) {
	out := new(LockAccountResponse)
	err := c.cc.Invoke(ctx, "/account_service.Account/LockAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) RequestUnlockAccount(ctx context.Context, in *RequestUnlockAccountRequest, opts ...grpc.CallOption) (*RequestUnlockAccountResponse, error) {
	out := new(RequestUnlockAccountResponse)
	err := c.cc.Invoke(ctx, "/account_service.Account/RequestUnlockAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) UnlockAccount(ctx context.Context, in *UnlockAccountRequest, opts ...grpc.CallOption) (*UnlockAccountResponse, error) {
	out := new(UnlockAccountResponse)
	err := c.cc.Invoke(ctx, "/account_service.Account/UnlockAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error) {
	out := new(ListUsersResponse)
	err := c.cc.Invoke(ctx, "/account_service.Account/ListUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountServer is the server API for Account service.
type AccountServer interface {
	CreateAccount(context.Context, *CreateAccountRequest) (*CreateAccountResponse, error)
	ResendActivationMail(context.Context, *ResendActivationMailRequest) (*ResendActivationMailResponse, error)
	ActivateAccount(context.Context, *ActivateAccountRequest) (*ActivateAccountResponse, error)
	UpdateAccount(context.Context, *UpdateAccountRequest) (*UpdateAccountResponse, error)
	DeleteAccount(context.Context, *DeleteAccountRequest) (*DeleteAccountResponse, error)
	GetAccount(context.Context, *GetAccountRequest) (*GetAccountResponse, error)
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	Logout(context.Context, *LogoutRequest) (*LogoutResponse, error)
	ResetPassword(context.Context, *ResetPasswordRequest) (*ResetPasswordResponse, error)
	LockAccount(context.Context, *LockAccountRequest) (*LockAccountResponse, error)
	RequestUnlockAccount(context.Context, *RequestUnlockAccountRequest) (*RequestUnlockAccountResponse, error)
	UnlockAccount(context.Context, *UnlockAccountRequest) (*UnlockAccountResponse, error)
	ListUsers(context.Context, *ListUsersRequest) (*ListUsersResponse, error)
}

// UnimplementedAccountServer can be embedded to have forward compatible implementations.
type UnimplementedAccountServer struct {
}

func (*UnimplementedAccountServer) CreateAccount(ctx context.Context, req *CreateAccountRequest) (*CreateAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAccount not implemented")
}
func (*UnimplementedAccountServer) ResendActivationMail(ctx context.Context, req *ResendActivationMailRequest) (*ResendActivationMailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResendActivationMail not implemented")
}
func (*UnimplementedAccountServer) ActivateAccount(ctx context.Context, req *ActivateAccountRequest) (*ActivateAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActivateAccount not implemented")
}
func (*UnimplementedAccountServer) UpdateAccount(ctx context.Context, req *UpdateAccountRequest) (*UpdateAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAccount not implemented")
}
func (*UnimplementedAccountServer) DeleteAccount(ctx context.Context, req *DeleteAccountRequest) (*DeleteAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAccount not implemented")
}
func (*UnimplementedAccountServer) GetAccount(ctx context.Context, req *GetAccountRequest) (*GetAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccount not implemented")
}
func (*UnimplementedAccountServer) Login(ctx context.Context, req *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedAccountServer) Logout(ctx context.Context, req *LogoutRequest) (*LogoutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Logout not implemented")
}
func (*UnimplementedAccountServer) ResetPassword(ctx context.Context, req *ResetPasswordRequest) (*ResetPasswordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResetPassword not implemented")
}
func (*UnimplementedAccountServer) LockAccount(ctx context.Context, req *LockAccountRequest) (*LockAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LockAccount not implemented")
}
func (*UnimplementedAccountServer) RequestUnlockAccount(ctx context.Context, req *RequestUnlockAccountRequest) (*RequestUnlockAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestUnlockAccount not implemented")
}
func (*UnimplementedAccountServer) UnlockAccount(ctx context.Context, req *UnlockAccountRequest) (*UnlockAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnlockAccount not implemented")
}
func (*UnimplementedAccountServer) ListUsers(ctx context.Context, req *ListUsersRequest) (*ListUsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUsers not implemented")
}

func RegisterAccountServer(s *grpc.Server, srv AccountServer) {
	s.RegisterService(&_Account_serviceDesc, srv)
}

func _Account_CreateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).CreateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account_service.Account/CreateAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).CreateAccount(ctx, req.(*CreateAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_ResendActivationMail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResendActivationMailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).ResendActivationMail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account_service.Account/ResendActivationMail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).ResendActivationMail(ctx, req.(*ResendActivationMailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_ActivateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivateAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).ActivateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account_service.Account/ActivateAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).ActivateAccount(ctx, req.(*ActivateAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_UpdateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).UpdateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account_service.Account/UpdateAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).UpdateAccount(ctx, req.(*UpdateAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_DeleteAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).DeleteAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account_service.Account/DeleteAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).DeleteAccount(ctx, req.(*DeleteAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_GetAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).GetAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account_service.Account/GetAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).GetAccount(ctx, req.(*GetAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account_service.Account/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account_service.Account/Logout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).Logout(ctx, req.(*LogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_ResetPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).ResetPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account_service.Account/ResetPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).ResetPassword(ctx, req.(*ResetPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_LockAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LockAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).LockAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account_service.Account/LockAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).LockAccount(ctx, req.(*LockAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_RequestUnlockAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestUnlockAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).RequestUnlockAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account_service.Account/RequestUnlockAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).RequestUnlockAccount(ctx, req.(*RequestUnlockAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_UnlockAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnlockAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).UnlockAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account_service.Account/UnlockAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).UnlockAccount(ctx, req.(*UnlockAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_ListUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).ListUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account_service.Account/ListUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).ListUsers(ctx, req.(*ListUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Account_serviceDesc = grpc.ServiceDesc{
	ServiceName: "account_service.Account",
	HandlerType: (*AccountServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAccount",
			Handler:    _Account_CreateAccount_Handler,
		},
		{
			MethodName: "ResendActivationMail",
			Handler:    _Account_ResendActivationMail_Handler,
		},
		{
			MethodName: "ActivateAccount",
			Handler:    _Account_ActivateAccount_Handler,
		},
		{
			MethodName: "UpdateAccount",
			Handler:    _Account_UpdateAccount_Handler,
		},
		{
			MethodName: "DeleteAccount",
			Handler:    _Account_DeleteAccount_Handler,
		},
		{
			MethodName: "GetAccount",
			Handler:    _Account_GetAccount_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _Account_Login_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _Account_Logout_Handler,
		},
		{
			MethodName: "ResetPassword",
			Handler:    _Account_ResetPassword_Handler,
		},
		{
			MethodName: "LockAccount",
			Handler:    _Account_LockAccount_Handler,
		},
		{
			MethodName: "RequestUnlockAccount",
			Handler:    _Account_RequestUnlockAccount_Handler,
		},
		{
			MethodName: "UnlockAccount",
			Handler:    _Account_UnlockAccount_Handler,
		},
		{
			MethodName: "ListUsers",
			Handler:    _Account_ListUsers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
